### ISSUE TITLE
Not working properly with Python 3.12.2

### ISSUE THREAD

**Issue by scorpionjacky** [HubSpot/hubspot-api-python#303] opened 2024-04-01 23:17 UTC
Env: MacOS, Python 3.12.2

pip install --upgrade hubspot-api-client

Collecting hubspot-api-client
  Downloading hubspot_api_client-9.0.0-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: urllib3>=1.15 in /Users/mikechen/.pyenv/versions/3.12.2/envs/aplosetl_dev/lib/python3.12/site-packages (from hubspot-api-client) (2.2.1)
Requirement already satisfied: six>=1.10 in /Users/mikechen/.pyenv/versions/3.12.2/envs/aplosetl_dev/lib/python3.12/site-packages (from hubspot-api-client) (1.16.0)
Requirement already satisfied: certifi in /Users/mikechen/.pyenv/versions/3.12.2/envs/aplosetl_dev/lib/python3.12/site-packages (from hubspot-api-client) (2024.2.2)
Requirement already satisfied: python-dateutil in /Users/mikechen/.pyenv/versions/3.12.2/envs/aplosetl_dev/lib/python3.12/site-packages (from hubspot-api-client) (2.9.0.post0)
Downloading hubspot_api_client-9.0.0-py3-none-any.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 13.7 MB/s eta 0:00:00a 0:00:01
Installing collected packages: hubspot-api-client
Successfully installed hubspot-api-client-9.0.0
Note: you may need to restart the kernel to use updated packages.

Python 3.12.2 (main, Mar 31 2024, 11:45:50) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from hubspot import HubSpot
>>> 
>>> api_client = HubSpot(access_token='xxxxxxxxxxxxxxxxxx')
>>> 
>>> dir(api_client)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'access_token', 'api_key', 'auth', 'automation', 'cms', 'communication_preferences', 'config', 'conversations', 'create', 'crm', 'events', 'files', 'marketing', 'settings', 'webhooks']
>>> 
>>> dir(api_client.crm)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mikechen/.pyenv/versions/aplosetl_dev/lib/python3.12/site-packages/hubspot/client.py", line 62, in crm
    from .discovery.crm.discovery import Discovery as CrmDiscovery
  File "/Users/mikechen/.pyenv/versions/aplosetl_dev/lib/python3.12/site-packages/hubspot/discovery/crm/discovery.py", line 1, in <module>
    from ..discovery_base import DiscoveryBase
  File "/Users/mikechen/.pyenv/versions/aplosetl_dev/lib/python3.12/site-packages/hubspot/discovery/discovery_base.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
>>> 

Note:

`dir(api_client.crm)` worked fine under 3.11.8

**Comment by ian-whitestone** [comment] 2024-04-08 21:23
Hit the same thing today! `setuptools` needs to be added as an explicit dependency to fix it.

**Comment by mike-optifino** [comment] 2024-04-22 19:07
Hi! I have the same issue. Is a any chance to include [this fix](https://github.com/HubSpot/hubspot-api-python/pull/257) in next release? Thanks in advance!
@alzheltkovskiy-hubspot

**Comment by alzheltkovskiy-hubspot** [comment] 2024-05-03 10:28
Hi everyone. We are going to fix it in new release. I will notify you when this happens.

**Comment by knyghty** [comment] 2024-06-13 10:33
It looks like this should be fixed by #257

**Comment by mikicz** [comment] 2024-06-27 13:49
Hey, any updates on this?

**Comment by alzheltkovskiy-hubspot** [comment] 2024-06-28 10:01
Hey @mikicz, still in progress.

**Comment by jesusch** [comment] 2024-08-11 11:25
any update?

**Comment by Zaffer** [comment] 2024-08-31 03:11
+1 please fix

**Comment by alzheltkovskiy-hubspot** [comment] 2024-09-02 06:40
Hi all. We going to fix it during the week.

**Comment by spenweb** [comment] 2024-09-04 04:09
> Hit the same thing today! `setuptools` needs to be added as an explicit dependency to fix it.
> 
> Not to suggest that is the right long term fix, but that will solve the issue in the short term.

I can confirm that installing `setuptools[core]==74.1.1` worked for me.

**Comment by knyghty** [comment] 2024-09-18 09:41
@alzheltkovskiy-hubspot thanks for the fix on this, do you have an idea when we can expect a new release?

**Comment by alzheltkovskiy-hubspot** [comment] 2024-10-10 10:15
Hey all! Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v.10.0.0)?

**Comment by knyghty** [comment] 2024-10-12 12:06
@alzheltkovskiy-hubspot I didn't thoroughly test but seems to be working for me, I no longer need to install setuptools.

**Closed** 2024-10-14 05:42 UTC
